---
abstract: 'split data-driven tests into several test scripts.'
author:
  - 'Shlomi Fish <shlomif@cpan.org>'
build_requires:
  File::Spec: '0'
  File::Temp: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Module::Build: '0.28'
  Test::Differences: '0'
  Test::More: '0'
  lib: '0'
  parent: '0'
  perl: '5.006'
configure_requires:
  Module::Build: '0.28'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-Data-Split
requires:
  IO::All: '0'
  List::MoreUtils: '0'
  MooX: '0'
  MooX::late: '0.010'
  autodie: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Test-Data-Split
  repository: https://github.com/shlomif/perl-Test-Data-Split.git
version: 0.0.1
